/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as RoomsRoomIdRouteRouteImport } from './routes/rooms/$roomId/route'
import { Route as RoomsRoomIdLiveRouteImport } from './routes/rooms/$roomId/live'
import { Route as RoomsRoomIdJoinRouteImport } from './routes/rooms/$roomId/join'
import { Route as RoomsRoomIdEndedRouteImport } from './routes/rooms/$roomId/ended'

const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRouteRoute = RoomsRoomIdRouteRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdLiveRoute = RoomsRoomIdLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => RoomsRoomIdRouteRoute,
} as any)
const RoomsRoomIdJoinRoute = RoomsRoomIdJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => RoomsRoomIdRouteRoute,
} as any)
const RoomsRoomIdEndedRoute = RoomsRoomIdEndedRouteImport.update({
  id: '/ended',
  path: '/ended',
  getParentRoute: () => RoomsRoomIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/rooms/$roomId': typeof RoomsRoomIdRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/rooms/$roomId/ended': typeof RoomsRoomIdEndedRoute
  '/rooms/$roomId/join': typeof RoomsRoomIdJoinRoute
  '/rooms/$roomId/live': typeof RoomsRoomIdLiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/rooms/$roomId': typeof RoomsRoomIdRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/rooms/$roomId/ended': typeof RoomsRoomIdEndedRoute
  '/rooms/$roomId/join': typeof RoomsRoomIdJoinRoute
  '/rooms/$roomId/live': typeof RoomsRoomIdLiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/rooms/$roomId': typeof RoomsRoomIdRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/rooms/$roomId/ended': typeof RoomsRoomIdEndedRoute
  '/rooms/$roomId/join': typeof RoomsRoomIdJoinRoute
  '/rooms/$roomId/live': typeof RoomsRoomIdLiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/rooms/$roomId'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/rooms/$roomId/ended'
    | '/rooms/$roomId/join'
    | '/rooms/$roomId/live'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/rooms/$roomId'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/rooms/$roomId/ended'
    | '/rooms/$roomId/join'
    | '/rooms/$roomId/live'
  id:
    | '__root__'
    | '/'
    | '/change-password'
    | '/rooms/$roomId'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/(auth)/signup'
    | '/(auth)/verify-email'
    | '/rooms/$roomId/ended'
    | '/rooms/$roomId/join'
    | '/rooms/$roomId/live'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  RoomsRoomIdRouteRoute: typeof RoomsRoomIdRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignupRoute: typeof authSignupRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId/live': {
      id: '/rooms/$roomId/live'
      path: '/live'
      fullPath: '/rooms/$roomId/live'
      preLoaderRoute: typeof RoomsRoomIdLiveRouteImport
      parentRoute: typeof RoomsRoomIdRouteRoute
    }
    '/rooms/$roomId/join': {
      id: '/rooms/$roomId/join'
      path: '/join'
      fullPath: '/rooms/$roomId/join'
      preLoaderRoute: typeof RoomsRoomIdJoinRouteImport
      parentRoute: typeof RoomsRoomIdRouteRoute
    }
    '/rooms/$roomId/ended': {
      id: '/rooms/$roomId/ended'
      path: '/ended'
      fullPath: '/rooms/$roomId/ended'
      preLoaderRoute: typeof RoomsRoomIdEndedRouteImport
      parentRoute: typeof RoomsRoomIdRouteRoute
    }
  }
}

interface RoomsRoomIdRouteRouteChildren {
  RoomsRoomIdEndedRoute: typeof RoomsRoomIdEndedRoute
  RoomsRoomIdJoinRoute: typeof RoomsRoomIdJoinRoute
  RoomsRoomIdLiveRoute: typeof RoomsRoomIdLiveRoute
}

const RoomsRoomIdRouteRouteChildren: RoomsRoomIdRouteRouteChildren = {
  RoomsRoomIdEndedRoute: RoomsRoomIdEndedRoute,
  RoomsRoomIdJoinRoute: RoomsRoomIdJoinRoute,
  RoomsRoomIdLiveRoute: RoomsRoomIdLiveRoute,
}

const RoomsRoomIdRouteRouteWithChildren =
  RoomsRoomIdRouteRoute._addFileChildren(RoomsRoomIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  RoomsRoomIdRouteRoute: RoomsRoomIdRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignupRoute: authSignupRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
